# This script creates <num_servers> puppet lab instances
- name: Adjust the number of running servers
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Start or Terminate
      local_action:
        module: ec2
        # You have to enter Your keypair name here
        key_name: brokcloud
        instance_type: t2.micro
        image: ami-ac5c7afe
        region: ap-southeast-1
        wait: yes
        # This is a security group I already had
        group: launch-wizard-1
        instance_tags:
          Name: puppetlab
        # We set this with -e num_servers=x on the commandline.
        # 0 means to kill all server
        exact_count: "{{ num_servers }}"
        count_tag:
          Name: puppetlab
      register: ec2
    - debug:
        var=ec2
    - name: Add all instances to inventory
      local_action: add_host name={{ item.public_ip }} groupname=puppetlab
      with_items: ec2.tagged_instances
    - name: Wait for SSH to come up on all instances
      local_action: wait_for host={{ item.public_ip }} port=22 delay=3 timeout=320 state=started
      with_items: ec2.tagged_instances


- name: Configure all servers
  hosts: puppetlab
  remote_user: ec2-user
  sudo: yes
  roles:
    - sudo
  tasks:
    - name: All security updates
      command: "yum -y upgrade --disablerepo=\\* --enablerepo=amzn-updates"
      ignore_errors: True
    - name: Install everything we need
      yum: name={{ item }} state=present
      with_items:
        - puppet
        - emacs
        - vim
    - name: Set ec2-user password to animal+paper binder+right+a number
      user: name=ec2-user password='$6$rounds=100000$uUBYDc6ZbqHV.kuw$dH6GgnYWJ8YzNe22qw6rIbfgE9Xc.h2d.Yqom2y0R.8Rf7xmIb0dwu6E/YQXV0zjIS5acFnojPhqg41ul.Bbl1'
    - name: reload sshd
      command: "service sshd reload"
