# This script is idempotent, so 
- name: Adjust the number of running servers
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Start or Terminate
      local_action:
        module: ec2
        # You have to enter Your keypair name here
        key_name: brokcloud
        instance_type: t2.micro
        image: ami-748e2903
        region: eu-west-1
        wait: yes
        # This is a security group I already had
        group: launch-wizard-1
        instance_tags:
          Name: webserver_demo
        # We set this with -e num_servers=x on the commandline.
        # 0 means to kill all server
        exact_count: "{{ num_servers }}"
        count_tag:
          Name: webserver_demo
      register: ec2
    - debug:
        var=ec2
    - name: Add all instances to inventory
      local_action: add_host name={{ item.public_ip }} groupname=webserver_demo
      with_items: ec2.tagged_instances
    - name: Wait for SSH to come up on all instances
      local_action: wait_for host={{ item.public_ip }} port=22 delay=3 timeout=320 state=started
      with_items: ec2.tagged_instances


- name: Configure all servers
  hosts: webserver_demo
  remote_user: ec2-user
  sudo: yes
  tasks:
    - name: All security updates
      command: "yum -y upgrade --disablerepo=\\* --enablerepo=amzn-updates"
      ignore_errors: True
    # Add some more tasks and roles
